#  vim:ts=2:sts=2:sw=2:et
#
#  Author: Hari Sekhon
#  Date: 2014-11-29 01:02:47 +0000 (Sat, 29 Nov 2014)
#
#  https://github.com/harisekhon/Dockerfiles
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#  to help improve or steer this or other code I publish
#
#  http://www.linkedin.com/in/harisekhon
#

version: ~> 1.0

matrix:
  include:

    - os: linux
      language: python
      python:
        - "2.7"

    - os: linux
      language: python
      python:
        - "3.7"

# GitHub Workflows has better badged stratification at a glance
#    - os: linux
#      dist: trusty
#      language: python
#      python:
#        - "2.7"

    # Travis CI doesn't support Python virtual envs on Mac OS X yet, workaround is to use generic and install to system python
    - os: osx
      language: generic

sudo: required

#env:
#  - DEBUG=1

notifications:
  email: false

#branches:
#  only:
#    - master

cache:
  directories:
    - .cache
    - bash-tools
    - pytools_checks

# avoid package checksum mismatches when installing packages
before_install:
  - sudo rm -f "${TRAVIS_ROOT}/etc/apt/apt.conf.d/99-travis-apt-proxy"
  - sudo rm -rf "${TRAVIS_ROOT}/var/lib/apt/lists/"*

install:
  - echo nothing to install

script:
  - travis_retry make test
